



// { title: 'All of Me',
//   song:
//    [ { root: 'C',
//        currentChord: 'maj7',
//        id: 3,
//        chords: [Object],
//        currentroot: 'C' },
//      { root: 'C',
//        currentChord: 'maj7',
//        id: 3,
//        chords: [Object],
//        currentroot: 'C' },
//      { root: 'E',
//        currentChord: '7',
//        id: 7,
//        chords: [Object],
//        currentroot: 'E' },
//      { root: 'E',
//        currentChord: '7',
//        id: 7,
//        chords: [Object],
//        currentroot: 'E' },
//      { root: 'A',
//        currentChord: '7',
//        id: 0,
//        chords: [Object],
//        currentroot: 'A' },
//      { root: 'A',
//        currentChord: '7',
//        id: 0,
//        chords: [Object],
//        currentroot: 'A' },
//      { root: 'D',
//        currentChord: 'm',
//        id: 5,
//        chords: [Object],
//        currentroot: 'D' },
//      { root: 'D',
//        currentChord: 'm7',
//        id: 5,
//        chords: [Object],
//        currentroot: 'D' } ] }